---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Prepare Package Repo
  ansible.builtin.include_tasks:
    file: 'repo.yml'

- name: Install librewolf
  ansible.builtin.include_tasks:
    file: 'install.yml'

- name: Optional set browser as default
  ansible.builtin.include_tasks:
    file: 'xdg.yml'
  when: librewolf__xdg_settings | bool
