---
- name: "Pulling list of packages that are already installed"
  ansible.builtin.package_facts:
    manager: "auto"

- name: Update apt repo-cache on debian/ubuntu hosts
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_pkg_mgr == "apt"

- name: Install requirements to add packages via https
  become: true
  ansible.builtin.apt:
    package: "{{ item }}"
    state: present
  loop:
    - "apt-transport-https"
    - "extrepo"

- name: Enable librewolf via extrepo
  become: true
  l3d.linux.extrepo:
    action: 'enable'
    repository: "librewolf"
  register: _librewolf_repo

- name: Update librewolf via extrepo
  become: true
  l3d.linux.extrepo:
    action: 'update'
    repository: "librewolf"
  changed_when: _librewolf_repo.changed

- name: Update apt repo-cache on debian/ubuntu hosts
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
